### PR TITLE
Added Docker integration

### PR DESCRIPTION
**Pull request by MrDienns**

### CODE REVIEW

**Comment by MrDienns** [comment]
I should probably also add a volume mount for the configuration 🤔

**Comment by MiniDigger** [comment]
> I should probably also add a volume mount for the configuration

we should use docker configs. Are those only available to swarm? has k8s smth like this?

**Comment by MrDienns** [comment]
> 
> 
> > I should probably also add a volume mount for the configuration
> 
> we should use docker configs. Are those only available to swarm? has k8s smth like this?

Kubernetes has config maps, which will work out of the box with the current sourcecode. The docker-compose file is purely there as local development environment. At least, that's the plan. Is swarm based around compose files?

Though keep in mind that Vertx will take care of loading all configuration files from all relevant places, including Kubernetes configuration maps, local config file, system variables and environment variables. With the volume mount for the configuration I just want to make it a bit easier to use the file configuration in combination with compose. I think adding a simple volume mount to the `./conf/` folder would be easiest.

**Comment by MiniDigger** [comment]
> Is swarm based around compose files?

yes

the issue with volumes is that you need to physically store them somewhere. for configs, docker swarm/k8s makes sure that your file is available on all nodes in the cluster. 
but if that file is just for local development anyways, I am fine with a volume (altho I don't see why I would even want to run it in docker locally)

**Comment by MrDienns** [comment]
> but if that file is just for local development anyways

Yes, it is.

> (altho I don't see why I would even want to run it in docker locally)

Because in the future, the bot will do plenty of work which will require additional services. For example, in the far future, it'll be integrated into our own restful API. Or, it'll use some kind of database like MySQL or Mongo for linking players between our website and in-game users. Simply stuff like that.

**Comment by MrDienns** [comment]
There, @MiniDigger volume is added and works. Had to made a small change to the Dockerfile as I had to configure the working directory, since Vertx will relatively look for a `conf/` directory.

**Pull request merged**
